### PR TITLE
fix: Don't fail if a status poll fails

### PR DESCRIPTION
**Pull request by dbkr**
This makes failures of the status check request non-fatal and keeps trying the same as if the poll returned 'in progress'. This will avoid the whole notarization failing if one of the polls fails because network connectivity fails, etc.

It's annoying that we can't tell what is a temporary vs. permanent failure, but I think it's probably safer to assume that all failures here are temporary. We know that the initial upload has already succeeded so this covers things like the system not having altool installed.

Fixes https://github.com/electron/electron-notarize/issues/12
This probably obsoletes https://github.com/electron/electron-notarize/pull/13

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Won't this infinite loop if the notarization actually failed?

**Comment by davej** [comment]
Noticed this failure 7 times in a row today on [ToDesktop](https://www.todesktop.com/). Thanks for the PR, I've patched my local version of `electron-notarize`. 🙂

**Comment by shiqi** [comment]
this looks better than limited retry but we should probably make a notion that with this change,
if apple service goes down like it did last time,
then the run will rely on external timeout settings to stop, otherwise it will just keep waiting.

**Comment by dbkr** [comment]
@shiqi if the whole service goes down then the initial upload will fail which will cause electron-notarize to exit. It will only keep retrying if the upload succeeds but the polls fail.

**Comment by shiqi** [comment]
@dbkr during the apple service outage most recently it didn't fail the upload, it was successfully uploaded but the polls kept return error code 239 and apple just kept them in a queue which takes hours to process.

**Comment by dbkr** [comment]
Ah ok, yes - I'd probably suggest adding a `--timeout` option for this case if people wanted to give up rather than wait hours, but this is probably one for a separate PR.

**Comment by tmacwill** [comment]
thanks for this fix!! will it be merged + released soon? I'm seeing a lot of `Failed to check status of notarization request` errors.

**Comment by SeungjongHan** [comment]
`npm install electron-notarize` doesn't reflect the codes changed. Is it something related to release version?

**Comment by mceachen** [comment]
> `npm install electron-notarize` doesn't reflect the codes changed. Is it something related to release version?

The last release for this module is from May. You'll need to pull in master in your package.json, something like

```
    "electron-notarize": "git://github.com/electron/electron-notarize.git#8731b4a",
```

**Comment by stevenroussey-privicy** [comment]
@SeungjongHan The code is in master, but there has not been a release since May, so you will need to create your own package and use that rather than npm until something is released.

**Comment by mceachen** [comment]
As a stopgap, I just released @mceachen/electron-notarize (which I will *not* maintain, it's only until this package is released). Remember to update the `require` in your `notarize.js`.

The module didn't compile with the current tsc, so I fixed that and submitted PR#20.

**Comment by MarshallOfSound** [comment]
Sorry folks, 99% of Electron's packages auto-release.  Looks like this repository is part of the 1% that doesn't 🤷‍♂ I'll release this tonight

**Comment by Slidemagic** [comment]
> Sorry folks, 99% of Electron's packages auto-release. Looks like this repository is part of the 1% that doesn't 🤷‍♂ I'll release this tonight

Thank you for all the work. Would you mind releasing the package for 0.2.1 as well? Thx.

**Pull request merged**
