### PR TITLE
Add ability to notarize dmg

### PR DESCRIPTION
**Pull request by APshenkin**
To provide signed and notirized DMG file.

https://stackoverflow.com/questions/58169485/is-a-dmg-required-to-be-notarised-to-pass-gatekeeper-on-catalina

Packed app should be notarised first and after packaging to dmg, we should sign and notarize dmg file

### CODE REVIEW

**Comment by malept** [comment]
Has this changed? https://github.com/electron/electron-notarize/pull/6#issuecomment-506039358

**Comment by APshenkin** [comment]
@malept oh, didn't saw this PR. Maybe it will be clear to add this information in project readme

**Comment by fp07** [comment]
Any update on this?

**Comment by troppoli** [comment]
> To provide signed and notirized DMG file.
> 
> https://stackoverflow.com/questions/58169485/is-a-dmg-required-to-be-notarised-to-pass-gatekeeper-on-catalina
> 
> Packed app should be notarised first and after packaging to dmg, we should sign and notarize dmg file

[I do not think that the app should get notarized first](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow)... 
_'you can put apps, kernel extensions, and other software in a container, like a disk image, and notarize the container. The notary service accepts disk images (UDIF format), signed flat installer packages, and ZIP archives. It processes nested containers as well, like packages inside a disk image.
...
The notary service generates a ticket for the top-level file that you specify, as well as for each nested file. For example, if you submit a disk image that contains a signed installer package with an app bundle inside, the notarization service generates tickets for the disk image, installer package, and app bundle.'_

**Comment by troppoli** [comment]
well I've just tried this on Big Sur and Catalina. The flow of sign/notarize the .app then making an unsigned disk image worked well for a developer id app.... I had assumed I'd need to sign the app, then sign/notarize the dmg based on earlier reading, but that does note seem to be the case.

**Pull request closed without merging**
